# Messages you can change.
discord_link: "https://discord.gg/ABCDEF"
discord_msg: "Click here to join the Discord!"
discord_rand: "Your random code is "
discord_expl: "Copy and paste this code inside the #link channel."

# Don't change this if you don't know what you're doing.
table_to_link: "to_link_users"
table_linked: "linked_users"

# Change this when you're ready.
jdbc_connection_string: "DEFAULT"

info:
  author: "Critical <3"
  version: 1.0
  website: "https://critical.lol/"